.\"*********************************************************
.\"
.\" revsh
.\" A remote access security tool for establishing reverse
.\" shells with terminal support. Additionally, revsh offers
.\" crypto tunneling, SOCKS proxies, and reverse VPNs for
.\" advanced pivoting.
.\"
.\" Copyright (c) 2013 @emptymonkey
.\"
.\" Permission is hereby granted, free of charge, to any
.\" person obtaining a copy of this software and associated
.\" documentation files (the "Software"), to deal in the
.\" Software without restriction, including without
.\" limitation the rights to use, copy, modify, merge,
.\" publish, distribute, sublicense, and/or sell copies of
.\" the Software, and to permit persons to whom the Software
.\" is furnished to do so, subject to the following
.\" conditions:
.\"
.\" The above copyright notice and this permission notice
.\" shall be included in all copies or substantial portions
.\" of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF
.\" ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
.\" TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
.\" PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT
.\" SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
.\" CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
.\" OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
.\" IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
.\" DEALINGS IN THE SOFTWARE.
.\"
.\"*********************************************************
.Dd September 25, 2016
.Dt REVSH 1
.Os Linux/FreeBSD
.\"*********************************************************
.Sh NAME
.Nm revsh
.Nd A reverse shell security tool for remote access and
data tunneling.
.\"*********************************************************
.Sh SYNOPSIS
.Sh DESCRIPTION
.Sh ENVIRONMENT
.Sh FILES
.Sh EXAMPLES
.Sh DIAGNOSTICS
.Sh COMPATIBILITY
.Sh SEE ALSO
.Sh STANDARDS
.Sh HISTORY
.Sh AUTHORS
.Sh BUGS
